name: Update build website on push

on:
  push:
    branches:
      - main  # Exécute ce workflow lorsque tu pushes sur la branche main (modifiable)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Set up Node.js environment
      uses: actions/setup-node@v4.0.4

    - name: Install dependencies
      run: npm install  # Change la commande si tu utilises yarn ou un autre package manager
      
    - name: Building website
      run: |
        npm run build

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        commit_message: Building website automated by github actions
        build_dir: build  # Dossier à publier sur GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
