name: Update README with API Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Exécution chaque semaine (dimanche à minuit)
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1

    - name: Install npm
      run: sudo apt-get install npm
    
    - name: Building website
      run: |
        npm run build ..

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *
        git commit -m "Mise à jour du build du site"
        git push
